First Nice PR :)
talihomz/Enumaruby pull request #2
Opened 2018-03-08 10:14 UTC by SavaVuckovic

Refactoring the code to fix issues pointed out in issue #1

2018-03-08 10:21 UTC, nidalaa commented
Another PR! So much happiness! 😍 

![awesome](https://user-images.githubusercontent.com/7466903/37145980-0a2fa45c-22f5-11e8-9645-62b27baa4712.gif)

2018-03-11 11:45 UTC, nidalaa reviewed
One comment. Other than that well done!

2018-03-11 11:45 UTC, nidalaa commented on spec/enumerable_extension_spec.rb
>      it "doesn't modify original array" do
I think my_each_with_index should also epate this spec from my_each https://github.com/talihomz/Enumaruby/pull/2/files#diff-95d934febaaa9135d9c567171be87643R15

As `my_each_with_index` does exactly the same thing as `my_each` and in addition handles indices.

2018-03-11 11:46 UTC, nidalaa requested changes
AS in comment above ☝️

2018-03-12 18:07 UTC, talihomz approved these changes
Good work Sava ^^

2018-03-12 18:07 UTC, merged

2018-03-16 07:04 UTC, nidalaa commented
@wahomekevin @SavaVuckovic why was it merged without a final 👍 from the reviewer? 😨

2018-03-16 07:06 UTC, talihomz commented
I thought we had finalized everything on this?

Also, since it is already done, what is the usual process for undoing such a review, and restoring to the original state?

2018-03-16 07:08 UTC, talihomz commented
I've gone ahead and clicked on the "revert" button. Is this the right way?